#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

interface='wlo1'
label=""

state="$(cat /sys/class/net/"$interface"/operstate)"

if [ "$state" == "up" ]; then
	echo "$label"
	echo "$label"
  echo "#46BE50"
  exit 0
fi

interface='eno1'

state="$(cat /sys/class/net/"$interface"/operstate)"

if [ "$state" == "up" ]; then
	echo "$label"
	echo "$label"
  echo "#46BE50"
  exit 0
fi

